import { StyleSheet } from 'react-native';

import { BrandFonts, type BrandPalette, type EntryType } from '@/constants/theme';

export const ONLINE_COLOR = '#3DDC84';

export const CAT_FILTERS: { type: EntryType | 'all'; label: string; color: string; sf: string }[] = [
  { type: 'all',     label: 'All',      color: '#5B4FE8', sf: 'square.grid.2x2.fill' },
  { type: 'watch',  label: 'TV & Film', color: '#FF6B6B', sf: 'film.stack' },
  { type: 'read',   label: 'Books',     color: '#5FA8FF', sf: 'book.closed.fill' },
  { type: 'play',   label: 'Games',     color: '#5FD9FF', sf: 'gamecontroller.fill' },
  { type: 'podcast',label: 'Podcasts',  color: '#C084FC', sf: 'mic.fill' },
  { type: 'listen', label: 'Music',     color: '#9B95AC', sf: 'headphones' },
];

export const STAT_CATEGORIES = [
  { type: 'watch' as EntryType, label: 'TV', sf: 'tv', color: '#FF6B6B', bg: '#FF6B6B18' },
  { type: 'play' as EntryType, label: 'Games', sf: 'gamecontroller.fill', color: '#5BC8F5', bg: '#5BC8F518' },
  { type: 'podcast' as EntryType, label: 'Podcasts', sf: 'mic.fill', color: '#C084FC', bg: '#C084FC18' },
  { type: 'listen' as EntryType, label: 'Music', sf: 'music.note', color: '#9B95AC', bg: '#9B95AC18' },
  { type: 'read' as EntryType, label: 'Books', sf: 'book.fill', color: '#5FA8FF', bg: '#5FA8FF18' },
];

export function createStyles(Brand: BrandPalette) {
  return StyleSheet.create({
    card: { backgroundColor: Brand.paper },
    contentPad: { paddingTop: 4, paddingBottom: 32, paddingHorizontal: 20 },
    headerRow: { flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 20 },
    avWrap: { position: 'relative' },
    avRing: {
      width: 90, height: 90, borderRadius: 45, borderWidth: 2.5, borderColor: Brand.trust,
      alignItems: 'center', justifyContent: 'center',
      backgroundColor: Brand.card,
    },
    avImg: { width: 82, height: 82, borderRadius: 41 },
    avFallback: { width: 82, height: 82, borderRadius: 41, backgroundColor: Brand.tlight, alignItems: 'center', justifyContent: 'center' },
    avFallbackText: { fontFamily: BrandFonts.syneExtraBold, fontSize: 29, color: Brand.ink },
    onlineDot: { position: 'absolute', bottom: 3, right: 3, width: 14, height: 14, borderRadius: 7, backgroundColor: ONLINE_COLOR, borderWidth: 2, borderColor: Brand.card },
    headerInfo: { flex: 1, minWidth: 0 },
    nameRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 2 },
    name: { fontFamily: BrandFonts.syneExtraBold, fontSize: 22, color: Brand.ink, flexShrink: 1 },
    iconBtn: { width: 30, height: 30, borderRadius: 15, backgroundColor: Brand.tlight, alignItems: 'center', justifyContent: 'center' },
    handle: { fontFamily: BrandFonts.interMedium, fontSize: 13, color: Brand.muted, marginBottom: 4 },
    mutualFollowers: { fontFamily: BrandFonts.interMedium, fontSize: 12, color: Brand.muted, marginBottom: 8 },
    activityPill: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Brand.tlight, borderRadius: 20, paddingVertical: 6, paddingHorizontal: 12, alignSelf: 'flex-start' },
    activityDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: ONLINE_COLOR },
    activityText: { fontFamily: BrandFonts.interMedium, fontSize: 13, color: Brand.trust },
    closeFriendBtnActive: { backgroundColor: '#E6F9EA', borderWidth: 1, borderColor: '#248A3D' },
    closeFriendBtnTextActive: { color: '#248A3D' },
    friendActionBtn: { backgroundColor: Brand.trust, borderRadius: 20, paddingVertical: 6, paddingHorizontal: 14 },
    friendActionBtnMuted: { backgroundColor: Brand.tlight, borderWidth: 1, borderColor: Brand.border },
    friendActionBtnText: { fontFamily: BrandFonts.syneBold, fontSize: 12.5, color: '#fff' },
    friendActionBtnTextMuted: { color: Brand.muted },
    badgesSection: { width: '100%', alignItems: 'center', marginBottom: 28 },
    badgesTitle: { fontFamily: BrandFonts.syneBold, fontSize: 13, color: Brand.ink, textTransform: 'uppercase', letterSpacing: 0.8, textAlign: 'center', marginBottom: 12 },
    badgesRow: { flexDirection: 'row', gap: 18, justifyContent: 'center' },
    badgeItem: { alignItems: 'center', width: 66 },
    badgeCircle: { width: 52, height: 52, borderRadius: 26, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
    badgeIcon: { fontSize: 22 },
    badgeName: { fontFamily: BrandFonts.interMedium, fontSize: 10, color: Brand.muted, textAlign: 'center', marginTop: 5 },
    badgesEmpty: { fontFamily: BrandFonts.interRegular, fontSize: 12, color: Brand.muted, textAlign: 'center' },
    tabRow: { flexDirection: 'row', width: '100%', marginBottom: 7, borderBottomWidth: 1, borderBottomColor: Brand.border },
    tab: { flex: 1, alignItems: 'center', paddingBottom: 8 },
    tabActive: { borderBottomWidth: 2.5, borderBottomColor: Brand.trust },
    tabLabel: { fontFamily: BrandFonts.interMedium, fontSize: 13, color: Brand.muted },
    tabLabelActive: { color: Brand.ink, fontFamily: BrandFonts.syneBold },
    tabContent: { width: '100%' },
    emptyText: { fontFamily: BrandFonts.interRegular, fontSize: 13, color: Brand.muted, textAlign: 'center', paddingVertical: 24 },

    // Feed tab
    chipScroll: {},
    chipRow: { flexDirection: 'row', gap: 4, paddingHorizontal: 0 },
    chipRowCentered: { justifyContent: 'center' },
    chip: { width: 54, paddingVertical: 7, borderRadius: 12, backgroundColor: Brand.card, borderWidth: 1, borderColor: Brand.border, alignItems: 'center', gap: 3 },
    chipIcon: { width: 17, height: 17 },
    chipText: { fontFamily: BrandFonts.syneBold, fontSize: 8.5, color: Brand.muted, textAlign: 'center' },
    chipTextActive: { color: '#fff' },
    feedSortRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12, marginBottom: 14 },
    feedSortLabel: { fontFamily: BrandFonts.interRegular, fontSize: 12.5, color: Brand.muted, marginRight: 2 },
    feedSortBtn: { borderWidth: 1.5, borderColor: Brand.border, borderRadius: 20, paddingVertical: 5, paddingHorizontal: 14 },
    feedSortBtnActive: { backgroundColor: Brand.ink, borderColor: Brand.ink },
    feedSortBtnText: { fontFamily: BrandFonts.syneBold, fontSize: 12, color: Brand.muted },
    feedSortBtnTextActive: { color: '#fff' },

    // Watchlist tab
    wlToggleRow: { flexDirection: 'row', backgroundColor: Brand.card, borderWidth: 1, borderColor: Brand.border, borderRadius: 50, padding: 4, marginBottom: 14, gap: 4 },
    wlToggleBtn: { flex: 1, paddingVertical: 9, borderRadius: 50, alignItems: 'center' },
    wlToggleBtnActive: { backgroundColor: Brand.trust },
    wlToggleTxt: { fontFamily: BrandFonts.syneBold, fontSize: 13, color: Brand.muted },
    wlToggleTxtActive: { color: '#fff' },
    wlAddBtn: { backgroundColor: Brand.trust, borderRadius: 50, paddingVertical: 11, alignItems: 'center', marginBottom: 16 },
    wlAddBtnText: { fontFamily: BrandFonts.syneBold, fontSize: 13.5, color: '#fff' },
    wlGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    wlGridItem: { width: '30.5%', alignItems: 'center' },
    wlPosterWrap: { width: '100%', position: 'relative', marginBottom: 7 },
    wlPoster: { width: '100%', aspectRatio: 2 / 3, borderRadius: 10, backgroundColor: Brand.border },
    wlPosterFallback: { alignItems: 'center', justifyContent: 'center', padding: 6 },
    wlPosterFallbackText: { fontFamily: BrandFonts.syneBold, fontSize: 9, color: Brand.muted, textAlign: 'center' },
    wlAvatar: { position: 'absolute', bottom: -6, left: 6, width: 24, height: 24, borderRadius: 12, backgroundColor: Brand.trust, borderWidth: 2, borderColor: Brand.card, alignItems: 'center', justifyContent: 'center' },
    wlAvatarText: { fontFamily: BrandFonts.syneBold, fontSize: 9, color: '#fff' },
    wlLogBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Brand.trust, borderRadius: 50, paddingVertical: 6, paddingHorizontal: 12 },
    wlLogBtnText: { fontFamily: BrandFonts.syneBold, fontSize: 11, color: '#fff' },
    unratedSection: { marginBottom: 20 },
    unratedHeader: { marginBottom: 12 },
    unratedHeaderTitle: { fontFamily: BrandFonts.syneBold, fontSize: 13, color: Brand.ink, marginBottom: 2 },
    unratedHeaderSub: { fontFamily: BrandFonts.interRegular, fontSize: 11.5, color: Brand.muted },
    unratedPosterWrap: { borderRadius: 12, borderWidth: 2, borderColor: Brand.trust },
    unratedPoster: { borderRadius: 10 },
    wlRateBtn: { backgroundColor: Brand.trust, borderRadius: 50, paddingVertical: 6, paddingHorizontal: 12, alignItems: 'center' },
    wlRateBtnText: { fontFamily: BrandFonts.syneBold, fontSize: 11, color: '#fff' },

    // Collection tab
    collSearchRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: Brand.card, borderRadius: 26, paddingLeft: 14, paddingRight: 6, marginBottom: 12, borderWidth: 1, borderColor: Brand.border },
    collSearchPlaceholder: { flex: 1, paddingVertical: 12, fontSize: 13.5, fontFamily: BrandFonts.interRegular, color: Brand.muted },
    collScanBtn: { width: 32, height: 32, borderRadius: 16, backgroundColor: Brand.trust, alignItems: 'center', justifyContent: 'center' },
    collCatRow: { flexDirection: 'row', backgroundColor: Brand.card, borderWidth: 1, borderColor: Brand.border, borderRadius: 14, padding: 4, marginBottom: 12, gap: 3 },
    collCatBtn: { flex: 1, paddingVertical: 7, borderRadius: 10, alignItems: 'center' },
    collCatBtnActive: { backgroundColor: Brand.ink },
    collCatLabel: { fontFamily: BrandFonts.syneBold, fontSize: 8, color: Brand.muted, marginTop: 2 },
    collCatLabelActive: { color: '#fff' },
    collCatCount: { fontFamily: BrandFonts.interRegular, fontSize: 8, color: Brand.muted, marginTop: 1 },
    collCatCountActive: { color: 'rgba(255,255,255,0.75)' },
    collSortRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 12 },
    collSortLabel: { fontSize: 12, color: Brand.muted, fontFamily: BrandFonts.interRegular },
    collSortBtn: { borderWidth: 1.5, borderColor: Brand.border, borderRadius: 20, paddingVertical: 4, paddingHorizontal: 11 },
    collSortBtnActive: { backgroundColor: Brand.ink, borderColor: Brand.ink },
    collSortBtnText: { fontFamily: BrandFonts.syneBold, fontSize: 11.5, color: Brand.muted },
    collSortBtnTextActive: { color: '#fff' },
    collGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    collGridItem: { width: '31%' },
    collGridImg: { width: '100%', aspectRatio: 2 / 3, borderRadius: 8, backgroundColor: Brand.border },
    collGridImgPlaceholder: { alignItems: 'center', justifyContent: 'center', padding: 6 },
    collGridImgPlaceholderText: { fontFamily: BrandFonts.syneBold, fontSize: 10, color: Brand.muted, textAlign: 'center' },
    collGridStars: { paddingTop: 4, paddingHorizontal: 2 },
    collGridStarText: { fontSize: 10, color: '#F59E0B', letterSpacing: 0.5 },

    // Stats tab
    statsBox: { flexDirection: 'row', alignItems: 'center', width: '100%', backgroundColor: Brand.card, borderWidth: 1, borderColor: Brand.border, borderRadius: 18, paddingVertical: 16, marginBottom: 8 },
    stat: { flex: 1, alignItems: 'flex-start', paddingHorizontal: 14 },
    statNumRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 6, marginBottom: 2 },
    statNum: { fontFamily: BrandFonts.syneExtraBold, fontSize: 20, color: Brand.ink },
    statNumAccent: { color: Brand.trust },
    statLbl: { fontFamily: BrandFonts.syneBold, fontSize: 9, color: Brand.muted, textTransform: 'uppercase', letterSpacing: 0.8, marginLeft: 20 },
    statSubLbl: { fontFamily: BrandFonts.interRegular, fontSize: 9, color: Brand.muted, marginTop: 1, marginLeft: 20 },
    statDiv: { width: 1, height: 36, backgroundColor: Brand.border },
    statSfIcon: { marginBottom: 4 },
    streakCard: { width: '100%', backgroundColor: Brand.card, borderRadius: 18, borderWidth: 1, borderColor: Brand.border, padding: 18, flexDirection: 'row', alignItems: 'center', gap: 0, marginBottom: 8 },
    streakLeft: { flex: 1, minWidth: 0 },
    streakFireCircle: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#FFF0E8', alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
    streakFireEmoji: { fontSize: 15 },
    streakDays: { fontFamily: BrandFonts.syneBold, fontSize: 14, color: Brand.ink, marginBottom: 3 },
    streakMsg: { fontFamily: BrandFonts.interRegular, fontSize: 12, color: Brand.muted, marginBottom: 14 },
    weekRow: { flexDirection: 'row', gap: 5 },
    weekDay: { alignItems: 'center', gap: 4 },
    weekDot: { width: 22, height: 22, borderRadius: 11, borderWidth: 1.5, borderColor: Brand.border, backgroundColor: 'transparent' },
    weekDotDone: { backgroundColor: Brand.trust, borderColor: Brand.trust },
    weekDotToday: { borderColor: Brand.trust, borderWidth: 2, backgroundColor: 'transparent' },
    weekLabel: { fontFamily: BrandFonts.interMedium, fontSize: 9, color: Brand.muted },
    streakDivider: { width: 1, height: '80%', backgroundColor: Brand.border, marginHorizontal: 16 },
    streakRight: { alignItems: 'center', justifyContent: 'center', minWidth: 70 },
    longestLabel: { fontFamily: BrandFonts.interRegular, fontSize: 11, color: Brand.muted, textAlign: 'center', marginBottom: 2 },
    longestDays: { fontFamily: BrandFonts.syneExtraBold, fontSize: 22, color: Brand.ink, lineHeight: 26 },
    longestUnit: { fontFamily: BrandFonts.interRegular, fontSize: 12, color: Brand.muted },
    statsCard: { width: '100%', backgroundColor: Brand.card, borderWidth: 1, borderColor: Brand.border, borderRadius: 18, padding: 12, marginBottom: 8 },
    statsCardTitle: { fontFamily: BrandFonts.syneBold, fontSize: 9, color: Brand.muted, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 10, flex: 1 },
    goalRow: { flexDirection: 'row', gap: 8, marginBottom: 0 },
    goalCard: { flex: 1, marginBottom: 0 },
    goalNum: { fontFamily: BrandFonts.syneExtraBold, fontSize: 16, color: Brand.trust, lineHeight: 20, marginTop: 4 },
    goalTarget: { fontFamily: BrandFonts.interRegular, fontSize: 12, color: Brand.muted },
    goalSub: { fontFamily: BrandFonts.interRegular, fontSize: 10, color: Brand.muted, marginTop: 2, marginBottom: 6 },
    goalBarRow: { flexDirection: 'row', flexWrap: 'nowrap', gap: 2, marginBottom: 4 },
    goalBlock: { flex: 1, height: 6, borderRadius: 2, backgroundColor: Brand.border },
    goalBlockFilled: { backgroundColor: Brand.trust },
    goalFooter: { fontFamily: BrandFonts.interRegular, fontSize: 10, color: Brand.muted },
    activeRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingVertical: 4 },
    activeRowBorder: { borderTopWidth: 1, borderTopColor: Brand.border },
    activeIcon: { width: 28, height: 28, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
    activeInfo: { flex: 1, minWidth: 0 },
    activeLabel: { fontFamily: BrandFonts.syneExtraBold, fontSize: 11, color: Brand.ink },
    activeSub: { fontFamily: BrandFonts.interRegular, fontSize: 10 },
    cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 8 },
    myTasteHeader: { alignItems: 'center', marginBottom: 14 },
    myTasteTitle: { fontFamily: BrandFonts.syneExtraBold, fontSize: 18, color: Brand.ink },
    myTasteSub: { fontFamily: BrandFonts.interRegular, fontStyle: 'italic', fontSize: 12, color: Brand.muted, marginTop: 2 },
    myTasteViewAll: { position: 'absolute', right: 0, top: 4 },
    myTasteViewAllText: { fontFamily: BrandFonts.syneBold, fontSize: 11, color: Brand.trust },
    top4Row: { flexDirection: 'row', justifyContent: 'space-between' },
    top4Item: { alignItems: 'center', flex: 1 },
    top4ImgWrap: { position: 'relative', marginBottom: 6 },
    top4Img: { width: 64, height: 64, borderRadius: 10 },
    top4ImgFallback: { backgroundColor: Brand.tlight, alignItems: 'center', justifyContent: 'center' },
    top4ImgFallbackText: { fontFamily: BrandFonts.syneExtraBold, fontSize: 22, color: Brand.ink },
    top4Badge: { position: 'absolute', bottom: -6, right: -6, backgroundColor: Brand.trust, borderRadius: 10, paddingVertical: 2, paddingHorizontal: 5 },
    top4BadgeText: { fontFamily: BrandFonts.syneBold, fontSize: 9.5, color: '#fff' },
    top4Name: { fontFamily: BrandFonts.syneBold, fontSize: 11.5, color: Brand.ink, textAlign: 'center', marginTop: 8 },
    top4Handle: { fontFamily: BrandFonts.interRegular, fontSize: 10, color: Brand.muted, textAlign: 'center' },
    catRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 7 },
    catIconBox: { width: 26, height: 26, borderRadius: 7, alignItems: 'center', justifyContent: 'center' },
    catLabel: { fontFamily: BrandFonts.syneBold, fontSize: 11, color: Brand.ink, flex: 1 },
    catBarBg: { width: 40, height: 4, backgroundColor: Brand.border, borderRadius: 2, overflow: 'hidden' },
    catBarFill: { height: '100%', borderRadius: 2 },
    catCount: { fontFamily: BrandFonts.interRegular, fontSize: 12, color: Brand.muted, width: 20, textAlign: 'right' },
    genreRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, marginBottom: 10 },
    genreRankWrap: { width: 26, paddingTop: 1 },
    genreRank: { fontFamily: BrandFonts.syneExtraBold, fontSize: 11 },
    genreInfo: { flex: 1, minWidth: 0 },
    genreNameRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 4 },
    genreName: { fontFamily: BrandFonts.syneBold, fontSize: 11, color: Brand.ink, flex: 1 },
    genreBarTrack: { height: 4, borderRadius: 2, backgroundColor: Brand.border, overflow: 'hidden' },
    genreBarFill: { height: '100%', borderRadius: 2 },
    genreCount: { fontFamily: BrandFonts.syneBold, fontSize: 11 },
    recentChipRow: { flexWrap: 'wrap', marginBottom: 12 },
    recentChip: { paddingVertical: 4, paddingHorizontal: 9, borderRadius: 20, backgroundColor: Brand.paper, borderWidth: 1, borderColor: Brand.border },
    recentChipActive: { backgroundColor: Brand.ink, borderColor: Brand.ink },
    recentChipText: { fontFamily: BrandFonts.interMedium, fontSize: 11.5, color: Brand.muted },
    recentChipTextActive: { color: Brand.paper },
    recentRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
    recentThumb: { width: 44, height: 44, borderRadius: 7 },
    recentThumbFallback: { backgroundColor: Brand.tlight },
    recentTitle: { flex: 1, fontFamily: BrandFonts.syneBold, fontSize: 13, color: Brand.ink },

    // Rate modal
    rateOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
    rateSheet: { backgroundColor: Brand.paper, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, gap: 16, paddingBottom: 40 },
    rateItemRow: { flexDirection: 'row', gap: 14, alignItems: 'center' },
    ratePoster: { width: 52, height: 72, borderRadius: 10, backgroundColor: Brand.border },
    rateTitle: { fontFamily: BrandFonts.syneExtraBold, fontSize: 16, color: Brand.ink, lineHeight: 21 },
    rateSub: { fontFamily: BrandFonts.interRegular, fontSize: 12.5, color: Brand.muted, marginTop: 2 },
    rateLabel: { fontFamily: BrandFonts.syneBold, fontSize: 11, color: Brand.muted, textTransform: 'uppercase', letterSpacing: 0.8 },
    rateNote: { borderWidth: 1.5, borderColor: Brand.border, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, fontFamily: BrandFonts.interRegular, color: Brand.ink, backgroundColor: Brand.card, minHeight: 52, textAlignVertical: 'top' },
    rateLogBtn: { backgroundColor: Brand.trust, borderRadius: 14, paddingVertical: 15, alignItems: 'center' },
    rateLogBtnDisabled: { opacity: 0.45 },
    rateLogBtnText: { fontFamily: BrandFonts.syneBold, fontSize: 16, color: '#fff' },
  });
}
